### ISSUE TITLE
Can't search the papers of an author

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-HAL#3]
The query [What are the papers of Donald E. Knuth?](http://askplatyp.us/?lang=en&q=What+are+the+papers+of+Donald+E.+Knuth%3F) fails although [Who wrote "The first cycles in an evolving graph"?](http://askplatyp.us/?lang=en&q=Who+wrote+%22The+first+cycles+in+an+evolving+graph%22%3F) answers `Donald E. Knuth`.

It would be even nicer if we could simply search "What are the papers of Donald Knuth?" or "What are the papers of Knuth?"

**Comment by progval** [comment]
You should blame the HAL API.

```
>>> params = {'fq': 'authFullName_s:Donald E. Knuth', 'wt': 'json', 'fl': 'title_s'}
>>> requests.get('http://api.archives-ouvertes.fr/search/', params=params).json()
{'response': {'docs': [], 'numFound': 0, 'start': 0}}
>>> params = {'fq': 'authFullName_s:Donald Knuth', 'wt': 'json', 'fl': 'title_s'}
>>> requests.get('http://api.archives-ouvertes.fr/search/', params=params).json()
{'response': {'docs': [], 'numFound': 0, 'start': 0}}
>>> params = {'fq': 'authFullName_s:Donald*Knuth', 'wt': 'json', 'fl': 'title_s'}
>>> requests.get('http://api.archives-ouvertes.fr/search/', params=params).json()
{'response': {'docs': [{'title_s': ['The first cycles in an evolving graph']}], 'numFound': 1, 'start': 0}}
```

**Comment by progval** [comment]
(And I know this since I wrote the plugin, I have the same issue with some papers of Eddy Caron too)

**Comment by marc-chevalier** [comment]
You just have to verify the author of all papers. This is not a big deal.

**Comment by progval** [comment]
Avez-vous dix minutes pour parler de complexité ?
